baseURL = "https://alexloukissas.com"
enableRobotsTXT = true
googleAnalytics = "282009340"
languageCode = "en-us"
paginate = 5
theme = "hugo-theme-hello-friend-ng"
title = "Alex Loukissas"

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"
defaultTheme = "light"
description = "Personal website and blog for Alex Loukissas"
homeSubtitle = "Engineer, startup nerd, analog car fan, home chef"
images = [""]
keywords = "homepage, blog"
showReadingTime = true

[params.logo]
logoCursorColor = "#10B981"
logoHomeLink = "/"
logoText = "cd /home/alex"

[[params.social]]
name = "twitter"
url = "https://twitter.com/aloukissas"

[[params.social]]
name = "github"
url = "https://github.com/aloukissas"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/futureartist"

[permalinks]
posts = "/posts/:year/:month/:title"

[author]
name = "Alex Loukissas"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
